### ISSUE TITLE
closest bug in ee_extra

### ISSUE THREAD

**Issue by csaybar** [r-earthengine/ee_extra#19]
```python
import ee, eemont, ee_extra
ee.Initialize()
S2 = ee.ImageCollection('MODIS/006/MCD12Q1').closest('2020-10-15')
S2.getInfo()

ee_extra.ImageCollection.core.closest(
    ee.ImageCollection('MODIS/006/MCD12Q1'), '2020-10-15'
).getInfo()
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/csaybar/.local/lib/python3.8/site-packages/ee/collection.py", line 127, in getInfo
    return super(Collection, self).getInfo()
  File "/home/csaybar/.local/lib/python3.8/site-packages/ee/computedobject.py", line 98, in getInfo
    return data.computeValue(self)
  File "/home/csaybar/.local/lib/python3.8/site-packages/ee/data.py", line 674, in computeValue
    return _execute_cloud_call(
  File "/home/csaybar/.local/lib/python3.8/site-packages/ee/data.py", line 336, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Element.get: Parameter 'object' is required.

**Comment by csaybar** [comment]
@davemlz

**Comment by davemlz** [comment]
`closest` is a expensive method since I have to sort the whole collection. To avoid this, I set a tolerance that the user can change. In the case of `'MODIS/006/MCD12Q1'`, that is a yearly product, the tolerance will not get it for `2020-10-15`, that's why it gets an error. If you change the tolerance and the units, it will get it:

```python
import ee, eemont, ee_extra

ee.Initialize()

S2 = ee.ImageCollection('MODIS/006/MCD12Q1').closest('2020-10-15',tolerance = 2,unit = "year")
S2.getInfo()

ee_extra.ImageCollection.core.closest(
    ee.ImageCollection('MODIS/006/MCD12Q1'), '2020-10-15', 2, "year"
).getInfo()
```

I'll add an error to make it clear to the user! :)

**Comment by davemlz** [comment]
I can't add a personalized error. Since everything works in `lazy`, the error can't be catched inside the function. Best I can do is to put a warning in the docs. F.

**Comment by csaybar** [comment]
sorry, my eemont  was not up to date!
