### ISSUE TITLE
inquiry in spectralindices

### ISSUE THREAD

**Issue by csaybar** [r-earthengine/ee_extra#20]
The arguments slope and intercept, which indices do they refer to?
https://eemont.readthedocs.io/en/0.2.4/classes/stubs/eemont.imagecollection.index.html
![image](https://user-images.githubusercontent.com/16768318/140631677-1034fd48-3367-4af6-9f6d-758cb2000eea.png)

**Comment by csaybar** [comment]
@davemlz

**Comment by davemlz** [comment]
Done!
