### ISSUE TITLE
why gamma argument is set in eemont but not in ee_extra?

### ISSUE THREAD

**Issue by csaybar** [r-earthengine/ee_extra#22]
@davemlz 

gamma arg is not defined in ee_extra but ee_mont has documentation about it. Is it a bug?

**gamma - eemont**
https://github.com/davemlz/eemont/blob/914612cd9e087997d64eb8e1c6e5515e2d469be9/eemont/imagecollection.py#L397

![image](https://user-images.githubusercontent.com/16768318/140636510-033c0246-c579-477f-8cce-ee709bd958a6.png)

**gamma - eeextra**

![image](https://user-images.githubusercontent.com/16768318/140636525-1da7e1f4-92f8-47b7-8b8c-bc6988c00b83.png)

**Comment by davemlz** [comment]
But `gamma` is there! xD

https://github.com/r-earthengine/ee_extra/blob/97ce4f25fb836aa0043260565d5faa5158eb32b7/ee_extra/Spectral/core.py#L32

https://github.com/r-earthengine/ee_extra/blob/97ce4f25fb836aa0043260565d5faa5158eb32b7/ee_extra/Spectral/core.py#L53

**Comment by csaybar** [comment]
hahahhaa, maldito reticulate >:v, disculpa XD
