### ISSUE TITLE
Add Landsat 8/9 tasseled cap coefficients

### ISSUE THREAD

**Issue by aazuspan** [r-earthengine/ee_extra#42]
Tasseled cap coefficients for Landsat 8/9 TOA and SR data were recently published by [Zhai et al](https://www.researchgate.net/publication/359299736_Conterminous_United_States_Landsat-8_top_of_atmosphere_and_surface_reflectance_tasseled_cap_transformation_coefficients). We already have Landsat 8 coefficients from [Baig et al](https://www.researchgate.net/publication/262005316_Derivation_of_a_tasselled_cap_transformation_based_on_Landsat_8_at-_satellite_reflectance), so I'll need to do some reading to see which to include...

**Comment by davemlz** [comment]
Hey @aazuspan!

That's nice! :rocket:  For L9 the coefs should be the same as L8, right?

PD: I also added L9 for the remaining features, like `spectralIndices` and `maskClouds`. However, Landsat 9 is not yet included in the GEE STAC (I don't know why) and the tests are broken. I will remove L9 from the tests for now and when L9 is added I'll also do it :)

Best,

David

**Comment by aazuspan** [comment]
Hey @davemlz, yep, the L8 coeffs should work for L9, at least until something gets published specifically based on L9 data :)

Thanks for the heads up on the STAC issue! I'll make sure to disable the L9 tasseled cap tests if I make a PR before that's added. 

Can't wait to have all the features up and running for L9!

**Comment by davemlz** [comment]
Hey @aazuspan, just to let you know that L9 is now in the STAC! :rocket:

**Comment by aazuspan** [comment]
Awesome, thanks @davemlz! PR incoming :)
